import { createTamagui } from '@tamagui/core'
import { shorthands } from '@tamagui/shorthands'
import { themes, tokens } from '@tamagui/themes'

const config = createTamagui({
  defaultFont: 'body',
  shouldAddPrefersColorThemes: true,
  themeClassNameOnRoot: true,
  shorthands,
  fonts: {
    body: {
      family: 'System',
      size: {
        1: 12,
        2: 14,
        3: 16,
        4: 18,
        5: 20,
        6: 24,
        7: 28,
        8: 32,
        9: 36,
        10: 40,
      },
      weight: {
        4: '300',
        6: '400',
        7: '600',
        8: '700',
        9: '800',
      },
      color: {
        6: '#222',
        7: '#666',
        8: '#888',
        9: '#999',
        10: '#aaa',
        11: '#ccc',
        12: '#fff',
      },
      letterSpacing: {
        4: 0,
        8: -1,
      },
      lineHeight: {
        1: 16,
        2: 20,
        3: 24,
        4: 28,
        5: 32,
        6: 36,
        7: 40,
        8: 44,
        9: 48,
        10: 52,
      },
    },
    heading: {
      family: 'System',
      size: {
        6: 24,
        7: 28,
        8: 32,
        9: 36,
        10: 40,
      },
      weight: {
        6: '400',
        7: '600',
        8: '700',
        9: '800',
      },
      letterSpacing: {
        6: -1,
        7: -1.5,
        8: -2,
        9: -2.5,
        10: -3,
      },
      lineHeight: {
        6: 28,
        7: 32,
        8: 36,
        9: 40,
        10: 44,
      },
    },
  },
  themes: {
    ...themes,
    dark: {
      background: '#222',
      backgroundHover: '#333',
      backgroundPress: '#444',
      backgroundFocus: '#333',
      borderColor: '#555',
      color: '#fff',
      colorHover: '#fff',
      colorPress: '#fff',
      colorFocus: '#fff',
      placeholderColor: '#888',
      preparar: '#FFF700',
      exercicio: '#7BFF7B',
      descansar: '#FF5C5C',
      descansoCiclo: '#FFD700',
    },
    light: {
      background: '#fff',
      backgroundHover: '#f5f5f5',
      backgroundPress: '#e5e5e5',
      backgroundFocus: '#f5f5f5',
      borderColor: '#ddd',
      color: '#222',
      colorHover: '#222',
      colorPress: '#222',
      colorFocus: '#222',
      placeholderColor: '#666',
      preparar: '#FFF700',
      exercicio: '#7BFF7B',
      descansar: '#FF5C5C',
      descansoCiclo: '#FFD700',
    },
  },
  tokens: {
    ...tokens,
    color: {
      ...tokens.color,
      preparar: '#FFF700',
      exercicio: '#7BFF7B',
      descansar: '#FF5C5C',
      descansoCiclo: '#FFD700',
      primary: '#FFF700',
      secondary: '#00BFFF',
      background: '#222',
      text: '#fff',
    },
    space: {
      ...tokens.space,
      0: 0,
      1: 4,
      2: 8,
      3: 12,
      4: 16,
      5: 20,
      6: 24,
      7: 28,
      8: 32,
      9: 36,
      10: 40,
    },
    size: {
      ...tokens.size,
      0: 0,
      1: 4,
      2: 8,
      3: 12,
      4: 16,
      5: 20,
      6: 24,
      7: 28,
      8: 32,
      9: 36,
      10: 40,
    },
    radius: {
      ...tokens.radius,
      0: 0,
      1: 4,
      2: 8,
      3: 12,
      4: 16,
      5: 20,
    },
  },
  media: {
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: 'none' },
    pointerCoarse: { pointer: 'coarse' },
  },
})

export type AppConfig = typeof config

declare module '@tamagui/core' {
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config 